- name: Ensure curl and tar are installed
  apt:
    name:
      - curl
      - xz-utils
      - tar
    state: present
    update_cache: yes

- name: Download Node.js {{ node_version }}
  get_url:
    url: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
    dest: "/tmp/node-v{{ node_version }}.tar.xz"

- name: Extract Node.js {{ node_version }}
  unarchive:
    src: "/tmp/node-v{{ node_version }}.tar.xz"
    dest: /usr/local
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Symlink Node.js and npm
  file:
    src: "/usr/local/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
  loop:
    - node
    - npm
    - npx