- name: Ensure curl is installed
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Add NodeSource APT key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodesource

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
    update_cache: yes